# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: pykindler

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest m2r
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run black --check .
      run: black --check .
    - name: If needed, commit black changes to the pull request
      if: failure()
      run: |
        black .
        git config --global user.name 'autoblack'
        git config --global user.email 'cclauss@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git checkout $GITHUB_HEAD_REF
        git commit -am "fixup: Format Python code with Black"
        git push
    - name: Test with unittest
      run: |
        python -m unittest discover -s ./pykindler/tests -v
    - name: Code Coverage Report
      uses: romeovs/lcov-reporter-action@v0.2.11
